# Define a 'Persistent Volume Claim' (PVC) for Mysql storage, dynamically provisioned cluster

apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim     # name of PVC, essentail for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Configure 'Deployment' of mysql server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database

spec:
  selector: # mysql Pod should contain some labels
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      containers:
        - image: mysql:8.0
          args:
            - "--ignore-db-dir=lost+found" # workaround for github
